import { readFile, writeFile, mkdir, readdir, unlink } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ICONS } from '../src/dom.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const assets = resolve(root, 'assets');
await mkdir(assets, { recursive: true });
const outputs = new Set();
function hash(value) { return createHash('sha256').update(value).digest('hex').slice(0, 12); }
async function asset(name, extension, contents) {
  const filename = `${name}.${hash(contents)}.${extension}`;
  await writeFile(resolve(assets, filename), contents); outputs.add(filename);
  return `assets/${filename}`;
}

const font = await asset('uicons-regular-rounded', 'woff2', await readFile(resolve(root, 'vendor/uicons/regular-rounded.woff2')));
const upstream = await readFile(resolve(root, 'vendor/uicons/source.css'), 'utf8');
const pages = await Promise.all(['index', 'editor'].map(name => readFile(resolve(root, `src/${name}.html`), 'utf8')));
const used = new Set([...Object.values(ICONS), ...pages.join('').matchAll(/fi-rr-([a-z0-9-]+)/g)].map(value => Array.isArray(value) ? value[1] : value));
let iconCss = `/* UIcons Regular Rounded; @flaticon/flaticon-uicons 3.3.1. See vendor/uicons/LICENSE.txt. */\n@font-face{font-family:Uicons;src:url("./${basename(font)}") format("woff2");font-display:block}\n[class^="fi-rr-"], [class*=" fi-rr-"]{font-style:normal}\n[class^="fi-rr-"]::before,[class*=" fi-rr-"]::before{font-family:Uicons!important;font-style:normal;font-weight:400!important;line-height:1;-webkit-font-smoothing:antialiased}\n`;
for (const name of [...used].sort()) {
  const rule = upstream.match(new RegExp(`\\.fi-rr-${name}:before\\{content:"(\\\\[a-f0-9]+)"\\}`));
  if (!rule) throw new Error(`Missing UIcons glyph: ${name}`);
  iconCss += `.fi-rr-${name}::before{content:"${rule[1]}"}\n`;
}
const icons = await asset('uicons', 'css', iconCss);
const bootstrap = await asset('bootstrap-5.3.8-rtl', 'css', (await readFile(resolve(root, 'vendor/bootstrap.rtl.min.css'), 'utf8')).replace(/\/\*# sourceMappingURL=.*?\*\//g, ''));
const rubik = await asset('rubik-variable', 'ttf', await readFile(resolve(root, 'vendor/rubik/Rubik-Variable.ttf')));
const buddies = await asset('learning-buddies', 'png', await readFile(resolve(root, 'src/visuals/learning-buddies.png')));
const style = await asset('app', 'css', (await readFile(resolve(root, 'src/styles.css'), 'utf8')).replaceAll('{{RUBIK}}', basename(rubik)));
const moduleCache = new Map();
async function moduleAsset(name) {
  if (moduleCache.has(name)) return moduleCache.get(name);
  let code = await readFile(resolve(root, 'src', name), 'utf8');
  for (const match of [...code.matchAll(/from ['"]\.\/([^'"]+\.mjs)['"]/g)]) {
    const dependency = await moduleAsset(match[1]);
    code = code.replaceAll(`./${match[1]}`, `./${basename(dependency)}`);
  }
  const path = await asset(basename(name, '.mjs'), 'js', code);
  moduleCache.set(name, path); return path;
}
const publicJs = await moduleAsset('public.mjs');
const editorJs = await moduleAsset('editor.mjs');
const replacements = { BOOTSTRAP: bootstrap, ICONS: icons, STYLE: style, PUBLIC: publicJs, EDITOR: editorJs, BUDDIES: buddies };
for (const [i, name] of ['index', 'editor'].entries()) {
  const html = pages[i].replace(/\{\{(\w+)\}\}/g, (_, key) => {
    if (!replacements[key]) throw new Error(`Unknown template asset: ${key}`);
    return replacements[key];
  });
  await writeFile(resolve(root, `${name}.html`), html);
}
// Only remove obsolete files generated by this builder, within the verified assets directory.
for (const name of await readdir(assets)) {
  if (/^[a-z0-9.-]+\.[a-f0-9]{12}\.(css|js|woff2|ttf|png)$/.test(name) && !outputs.has(name)) await unlink(resolve(assets, name));
}
await writeFile(resolve(assets, 'manifest.json'), JSON.stringify({ version: '1.0.0', bootstrap: '5.3.8', uicons: '3.3.1', files: [...outputs].sort() }, null, 2) + '\n');
console.log(`Built index.html and editor.html; ${outputs.size} assets with content hashes.`);
